apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-backend
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1        # Max extra pods during update
      maxUnavailable: 0
  replicas: 2
  selector:
    matchLabels:
      app: go-backend
  template:
    metadata:
      labels:
        app: go-backend
    spec:
      containers:
      - name: go-backend
        imagePullPolicy: Always
        image: d1zero/golang-app:latest # Replace with your Docker image
        ports:
        - containerPort: 8080 # Adjust to your app's port
        env:
        - name: DB_HOST
          value: "postgres" # Matches the PostgreSQL Service name
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: "mydb"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: password
        livenessProbe:
          httpGet:
            path: /health # Adjust to your app's health endpoint
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 10
