apiVersion: v1
kind: Service
metadata:
  name: go-backend
spec:
  selector:
    app: go-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP # Use LoadBalancer or NodePort for external access
